package com.zkingsoft.dao.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zkingsoft.model.sys.SysDbBackup;
import com.zkingsoft.pojo.PaginationVO;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 17:45
 */


public interface SysDbBackupDao{

	public int insert(SysDbBackup sysDbBackup);
   	
	public int update(SysDbBackup sysDbBackup);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long buId);

	public int deleteByModel(@Param("record") SysDbBackup sysDbBackup);
	
	public List<SysDbBackup> selectInPage(@Param("record") SysDbBackup sysDbBackup, @Param("pageVo") PaginationVO pageVo);

	public List<SysDbBackup> selectByModel(@Param("record") SysDbBackup sysDbBackup);
	
	public int  selectTotalRecord(@Param("record") SysDbBackup sysDbBackup);
	
	public SysDbBackup  selectById(Long buId);
	
}