package com.zkingsoft.actions.visitor;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.fileupload.FileUploadException;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import com.baidu.ueditor.ActionEnter;
import com.zkingsoft.constraint.BaseController;
import com.zkingsoft.pojo.AjaxResult;
import com.zkingsoft.util.ImageUtil;

/**
 * This field was generated by Zking.software.Codegen.
 * 
 * @date 2016-11-28 15:14
 */
@Controller
@RequestMapping(value = "/baidu/uploadFile")
public class BaiduFileUploadController extends BaseController {
	Logger log = Logger.getLogger(BaiduFileUploadController.class);

	@Value("${file_storage_path}")
	private String fileStoragePath;
	@Value("${nginx_url}")
	private String nginxUrl;
	// 最大文件大小
	private long maxSize = 1024 * 1024 * 5;
	private String fileTypeImg = "image";
	// 定义文件上传类型
	public static HashMap<String, String> extMap = new HashMap<String, String>();
	static {
		extMap.put("image", "gif,jpg,jpeg,png,bmp,ico");
		extMap.put("flash", "swf,flv");
		extMap.put("media", "swf,flv,mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb");
		extMap.put("file", "doc,docx,xls,xlsx,ppt,htm,html,txt,zip,rar,gz,bz2,pdf");
	}

	/**
	 * 通用的图上传action 本方法目前只能支持单文件上传，如果需要多文件还要好好想想
	 * 
	 * @author jiangyouyao
	 */
	@RequestMapping(value = "/doUpload")
	public void doFileUpload(HttpServletResponse response, MultipartHttpServletRequest request)
			throws IOException, FileUploadException {
		request.setCharacterEncoding("utf-8");
		response.setHeader("Content-Type", "text/html");
		PrintWriter out = null;

		String rootPath = request.getSession().getServletContext().getRealPath("/");
		out = response.getWriter();
		out.write(new ActionEnter(request, rootPath).exec());

	}

	/**
	 * 图片转换base64-png
	 */
	@RequestMapping(value = "/base64Image2Png")
	public @ResponseBody AjaxResult base64Image2Png(String base64Image) {
		// 判断文件是否存在
		String url = ImageUtil.base64Image2Png(base64Image, fileStoragePath, nginxUrl);
		log.info(url);
		AjaxResult result = new AjaxResult(AjaxResult.STATUS_OK, null, url);
		return result;
	}

}