package com.zkingsoft.services.web;

import java.util.List;

import com.zkingsoft.constraint.BaseServices;
import com.zkingsoft.model.web.WebAd;
import com.zkingsoft.pojo.PaginationVO;

/**
 * This field was generated by Zking.software.Codegen.
 * 
 * @date 2016-12-20 15:50
 */
public interface WebAdService extends BaseServices<WebAd> {

	/**
	 * 新增WebAd
	 * 
	 */
	public int add(WebAd webAd);

	/**
	 * 批量新增WebAd
	 * 
	 */
	public int batchAdd(List<WebAd> webAdList);

	/**
	 * 根据map键值对 更新WebAd
	 * 
	 */
	public int modifyByMap(WebAd oldWebAd, WebAd newWebAd);

	/**
	 * 根据对象 更新WebAd
	 * 
	 */
	public int modifyByModel(WebAd webAd);

	/**
	 * 批量删除WebAd
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除WebAd
	 * 
	 */
	public int removeById(Long adId);

	/**
	 * 根据对象删除WebAd
	 * 
	 */
	public int removeByModel(WebAd webAd);

	/**
	 * 分页查询WebAd
	 * 
	 */
	public List<WebAd> findInPage(WebAd webAd, PaginationVO pageVo);

	/**
	 * 根据对象查询WebAd
	 * 
	 */
	public List<WebAd> findByModel(WebAd webAd);

	/**
	 * 统计记录数WebAd
	 * 
	 */
	public int findTotal(WebAd webAd);

	/**
	 * 根据id查询WebAd
	 * 
	 */
	public WebAd findById(Long adId);

	/**
	 * 
	 * @Description: 查询广告栏中对应的广告，只查容量内的
	 */
	public List<WebAd> findAdByCloCode(String code);

	public WebAd findAdByCloCodeOne(String code);
}