package com.zkingsoft.services.web;

import java.util.List;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.web.WebMsg;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2017-01-11 13:38
 */
public interface WebMsgService  extends BaseServices<WebMsg>{
	
	/**
	 * 新增WebMsg
	 * 
	 */
	public int add(WebMsg webMsg);
   	
   	/**
	 * 批量新增WebMsg
	 * 
	 */
	public int batchAdd(List<WebMsg>  webMsgList);
   	
   	/**
	 * 根据map键值对 更新WebMsg
	 * 
	 */
	public int modifyByMap(WebMsg oldWebMsg ,WebMsg newWebMsg);
	
	/**
	 * 根据对象 更新WebMsg
	 * 
	 */
	public int modifyByModel(WebMsg webMsg);
	
	/**
	 * 批量删除WebMsg
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除WebMsg
	 * 
	 */
	public int removeById(Long msgId);
	
	/**
	 * 根据对象删除WebMsg
	 * 
	 */
	public int removeByModel(WebMsg webMsg);
	
	/**
	 * 分页查询WebMsg
	 * 
	 */
	public List<WebMsg> findInPage(WebMsg webMsg, PaginationVO pageVo);

	/**
	 * 根据对象查询WebMsg
	 * 
	 */
	public List<WebMsg> findByModel(WebMsg webMsg);
	
	/**
	 * 统计记录数WebMsg
	 * 
	 */
	public int  findTotal(WebMsg webMsg);
	
	/**
	 * 根据id查询WebMsg
	 * 
	 */
	public WebMsg  findById(Long msgId);

   	

  
}