package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.web.WebAdcolumn;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-20 15:50
 */


public interface WebAdcolumnDao{

	public int insert(WebAdcolumn webAdcolumn);
   	
   	public int batchInsert(@Param("list") List<WebAdcolumn> webAdcolumnList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(WebAdcolumn webAdcolumn);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long colId);

	public int deleteByModel(@Param("record") WebAdcolumn webAdcolumn);
	
	public List<WebAdcolumn> selectInPage(@Param("record") WebAdcolumn webAdcolumn, @Param("pageVo") PaginationVO pageVo);

	public List<WebAdcolumn> selectByModel(@Param("record") WebAdcolumn webAdcolumn);
	
	public int  selectTotalRecord(@Param("record") WebAdcolumn webAdcolumn);
	
	public WebAdcolumn  selectById(Long colId);
	
	public WebAdcolumn  selectForUpdate(Long colId);

	public List<WebAdcolumn> selectRemark();
	
}