package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.web.WebAd;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-20 15:50
 */


public interface WebAdDao{

	public int insert(WebAd webAd);
   	
   	public int batchInsert(@Param("list") List<WebAd> webAdList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(WebAd webAd);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long adId);

	public int deleteByModel(@Param("record") WebAd webAd);
	
	public List<WebAd> selectInPage(@Param("record") WebAd webAd, @Param("pageVo") PaginationVO pageVo);

	public List<WebAd> selectByModel(@Param("record") WebAd webAd);
	
	public int  selectTotalRecord(@Param("record") WebAd webAd);
	
	public WebAd  selectById(Long adId);
	
	public WebAd  selectForUpdate(Long adId);

	public List<WebAd> selectAdByCloCode(@Param("code")String code, @Param("capacity")Integer capacity);
	
}