package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.web.WebImages;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2017-02-12 20:19
 */


public interface WebImagesDao{

	public int insert(WebImages webImages);
   	
   	public int batchInsert(@Param("list") List<WebImages> webImagesList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(@Param("record")WebImages webImages);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long id);

	public int deleteByModel(@Param("record") WebImages webImages);
	
	public List<WebImages> selectInPage(@Param("record") WebImages webImages, @Param("pageVo") PaginationVO pageVo);

	public List<WebImages> selectByModel(@Param("record") WebImages webImages);
	
	public int  selectTotalRecord(@Param("record") WebImages webImages);
	
	public WebImages  selectById(Long id);
	
	public WebImages  selectForUpdate(Long id);
	
}