package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.web.WebMsg;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2017-01-11 13:49
 */


public interface WebMsgDao{

	public int insert(WebMsg webMsg);
   	
   	public int batchInsert(@Param("list") List<WebMsg> webMsgList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(@Param("record")WebMsg webMsg);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long msgId);

	public int deleteByModel(@Param("record") WebMsg webMsg);
	
	public List<WebMsg> selectInPage(@Param("record") WebMsg webMsg, @Param("pageVo") PaginationVO pageVo);

	public List<WebMsg> selectByModel(@Param("record") WebMsg webMsg);
	
	public int  selectTotalRecord(@Param("record") WebMsg webMsg);
	
	public WebMsg  selectById(Long msgId);
	
	public WebMsg  selectForUpdate(Long msgId);
	
}