package com.zkingsoft.services.bus;

import java.util.List;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.bus.BusCform;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-28 10:12
 */
public interface BusCformService  extends BaseServices<BusCform>{
	
	/**
	 * 新增BusCform
	 * 
	 */
	public int add(BusCform busCform);
   	
   	/**
	 * 批量新增BusCform
	 * 
	 */
	public int batchAdd(List<BusCform>  busCformList);
   	
   	/**
	 * 根据map键值对 更新BusCform
	 * 
	 */
	public int modifyByMap(BusCform oldBusCform ,BusCform newBusCform);
	
	/**
	 * 根据对象 更新BusCform
	 * 
	 */
	public int modifyByModel(BusCform busCform);
	
	/**
	 * 批量删除BusCform
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除BusCform
	 * 
	 */
	public int removeById(Long cfId);
	
	/**
	 * 根据对象删除BusCform
	 * 
	 */
	public int removeByModel(BusCform busCform);
	
	/**
	 * 分页查询BusCform
	 * 
	 */
	public List<BusCform> findInPage(BusCform busCform, PaginationVO pageVo);

	/**
	 * 根据对象查询BusCform
	 * 
	 */
	public List<BusCform> findByModel(BusCform busCform);
	
	/**
	 * 统计记录数BusCform
	 * 
	 */
	public int  findTotal(BusCform busCform);
	
	/**
	 * 根据id查询BusCform
	 * 
	 */
	public BusCform  findById(Long cfId);

   	

  
}