package com.zkingsoft.model.web;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.zkingsoft.anotations.Extend;
import com.zkingsoft.util.DateUtils;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-20 15:50
 */
public class WebAd implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  adId;
			
	
	/**
	 * 所属分类
	 */
	private Long  adColumn;
			
	
	private String  adTitle;
			
	
	private String  adUrl;
			
	@DateTimeFormat(pattern=DateUtils.DATE_FORMAT_DD)
	private Date  adTime;
	
	private String adImg;
			
	
	private Integer  adSequence;
			
	
	private String  adInfo1;
			
	
	private String  adInfo2;
			
	
	private String  adInfo3;
			
	
	private String  adInfo4;
			
	
	private String  adInfo5;
			
	
	private String  adInfo6;
	
	/**栏目名称*/
	@Extend
	private String colName;
	
	

	public String getColName() {
		return colName;
	}

	public void setColName(String colName) {
		this.colName = colName;
	}

	public Long getAdId() {
		return adId;
	}
   	
   	public void setAdId(Long adId) {
		this.adId=adId;
	}
   	

	public Long getAdColumn() {
		return adColumn;
	}
   	
   	public void setAdColumn(Long adColumn) {
		this.adColumn=adColumn;
	}
   	

	public String getAdTitle() {
		return adTitle;
	}
   	
   	public void setAdTitle(String adTitle) {
		this.adTitle=adTitle;
	}
   	

	public String getAdUrl() {
		return adUrl;
	}
   	
   	public void setAdUrl(String adUrl) {
		this.adUrl=adUrl;
	}
   	

	public Date getAdTime() {
		return adTime;
	}
   	
   	public void setAdTime(Date adTime) {
		this.adTime=adTime;
	}
   	

	public Integer getAdSequence() {
		return adSequence;
	}
   	
   	public void setAdSequence(Integer adSequence) {
		this.adSequence=adSequence;
	}
   	

	public String getAdInfo1() {
		return adInfo1;
	}
   	
   	public void setAdInfo1(String adInfo1) {
		this.adInfo1=adInfo1;
	}
   	

	public String getAdInfo2() {
		return adInfo2;
	}
   	
   	public void setAdInfo2(String adInfo2) {
		this.adInfo2=adInfo2;
	}
   	

	public String getAdInfo3() {
		return adInfo3;
	}
   	
   	public void setAdInfo3(String adInfo3) {
		this.adInfo3=adInfo3;
	}
   	

	public String getAdInfo4() {
		return adInfo4;
	}
   	
   	public void setAdInfo4(String adInfo4) {
		this.adInfo4=adInfo4;
	}
   	

	public String getAdInfo5() {
		return adInfo5;
	}
   	
   	public void setAdInfo5(String adInfo5) {
		this.adInfo5=adInfo5;
	}
   	

	public String getAdInfo6() {
		return adInfo6;
	}
   	
   	public void setAdInfo6(String adInfo6) {
		this.adInfo6=adInfo6;
	}
   	

	public String getAdImg() {
		return adImg;
	}

	public void setAdImg(String adImg) {
		this.adImg = adImg;
	}

	@Override
	public String toString() {
		return "{WebAd:{"
		+"adId:"+adId+","
		+"adColumn:"+adColumn+","
		+"adTitle:"+adTitle+","
		+"adUrl:"+adUrl+","
		+"adTime:"+adTime+","
		+"adSequence:"+adSequence+","
		+"adInfo1:"+adInfo1+","
		+"adInfo2:"+adInfo2+","
		+"adInfo3:"+adInfo3+","
		+"adInfo4:"+adInfo4+","
		+"adInfo5:"+adInfo5+","
		+"adInfo6:"+adInfo6+","
		+"}}";
	}


  
}