package com.zkingsoft.model.web;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-20 15:50
 */
public class WebAdcolumn implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  colId;
			
	
	private String  colName;
			
	
	private String  colRemark;
	
	/**
	 * 广告栏标示
	 */
	private String code;
	
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	/**
	 * 容量
	 */
	private Integer  colCapacity;
			
	

	public Long getColId() {
		return colId;
	}
   	
   	public void setColId(Long colId) {
		this.colId=colId;
	}
   	

	public String getColName() {
		return colName;
	}
   	
   	public void setColName(String colName) {
		this.colName=colName;
	}
   	

	public String getColRemark() {
		return colRemark;
	}
   	
   	public void setColRemark(String colRemark) {
		this.colRemark=colRemark;
	}
   	

	public Integer getColCapacity() {
		return colCapacity;
	}
   	
   	public void setColCapacity(Integer colCapacity) {
		this.colCapacity=colCapacity;
	}
   	

	@Override
	public String toString() {
		return "{WebAdcolumn:{"
		+"colId:"+colId+","
		+"colName:"+colName+","
		+"colRemark:"+colRemark+","
		+"colCapacity:"+colCapacity+","
		+"}}";
	}


  
}