package com.zkingsoft.model.web;

import java.util.Date;
import java.io.Serializable;
import com.zkingsoft.anotations.Extend;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2017-02-12 20:19
 */
public class WebImages implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  id;
			
	
	private Long  artId;
			
	
	private String  name;
			
	
	private String  path;
			
	
	private Date  time;
			
	
	private String  info1;
			
	
	private String  info2;
			
	
	private String  info3;
			
	

	public Long getId() {
		return id;
	}
   	
   	public void setId(Long id) {
		this.id=id;
	}
   	

	public Long getArtId() {
		return artId;
	}
   	
   	public void setArtId(Long artId) {
		this.artId=artId;
	}
   	

	public String getName() {
		return name;
	}
   	
   	public void setName(String name) {
		this.name=name;
	}
   	

	public String getPath() {
		return path;
	}
   	
   	public void setPath(String path) {
		this.path=path;
	}
   	

	public Date getTime() {
		return time;
	}
   	
   	public void setTime(Date time) {
		this.time=time;
	}
   	

	public String getInfo1() {
		return info1;
	}
   	
   	public void setInfo1(String info1) {
		this.info1=info1;
	}
   	

	public String getInfo2() {
		return info2;
	}
   	
   	public void setInfo2(String info2) {
		this.info2=info2;
	}
   	

	public String getInfo3() {
		return info3;
	}
   	
   	public void setInfo3(String info3) {
		this.info3=info3;
	}
   	

	@Override
	public String toString() {
		return "{WebImages:{"
		+"id:"+id+","
		+"artId:"+artId+","
		+"name:"+name+","
		+"path:"+path+","
		+"time:"+time+","
		+"info1:"+info1+","
		+"info2:"+info2+","
		+"info3:"+info3+","
		+"}}";
	}


  
}