package com.zkingsoft.model.web;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
import java.util.Date;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2017-01-11 13:38
 */
public class WebMsg implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  msgId;
			
	
	/**
	 * 留言类型
	 */
	private String  msgType;
			
	
	/**
	 * 联系人名称
	 */
	private String  msgUserName;
			
	
	/**
	 * 联系电话
	 */
	private String  msgTel;
			
	
	/**
	 * 联系地址
	 */
	private String  msgAddress;
			
	
	/**
	 * 留言内容
	 */
	private String  msgContent;
	
	/**
	 * 创建时间
	 * 
	 */
	private Date createTime;
			
	
	private String  info1;
			
	
	private String  info2;
			
	
	private String  info3;
			
	

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getMsgId() {
		return msgId;
	}
   	
   	public void setMsgId(Long msgId) {
		this.msgId=msgId;
	}
   	

	public String getMsgType() {
		return msgType;
	}
   	
   	public void setMsgType(String msgType) {
		this.msgType=msgType;
	}
   	

	public String getMsgUserName() {
		return msgUserName;
	}
   	
   	public void setMsgUserName(String msgUserName) {
		this.msgUserName=msgUserName;
	}
   	

	public String getMsgTel() {
		return msgTel;
	}
   	
   	public void setMsgTel(String msgTel) {
		this.msgTel=msgTel;
	}
   	

	public String getMsgAddress() {
		return msgAddress;
	}
   	
   	public void setMsgAddress(String msgAddress) {
		this.msgAddress=msgAddress;
	}
   	

	public String getMsgContent() {
		return msgContent;
	}
   	
   	public void setMsgContent(String msgContent) {
		this.msgContent=msgContent;
	}
   	

	public String getInfo1() {
		return info1;
	}
   	
   	public void setInfo1(String info1) {
		this.info1=info1;
	}
   	

	public String getInfo2() {
		return info2;
	}
   	
   	public void setInfo2(String info2) {
		this.info2=info2;
	}
   	

	public String getInfo3() {
		return info3;
	}
   	
   	public void setInfo3(String info3) {
		this.info3=info3;
	}
   	

	@Override
	public String toString() {
		return "{WebMsg:{"
		+"msgId:"+msgId+","
		+"msgType:"+msgType+","
		+"msgUserName:"+msgUserName+","
		+"msgTel:"+msgTel+","
		+"msgAddress:"+msgAddress+","
		+"msgContent:"+msgContent+","
		+"info1:"+info1+","
		+"createTime:"+createTime+","
		+"info2:"+info2+","
		+"info3:"+info3+","
		+"}}";
	}


  
}