package com.zkingsoft.actions.admin.sys;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zkingsoft.anotations.RemoveRequestToken;
import com.zkingsoft.anotations.SaveRequestToken;
import com.zkingsoft.authority.Authority;
import com.zkingsoft.authority.MatrixAdapter;
import com.zkingsoft.constraint.BaseController;
import com.zkingsoft.model.sys.SysDataDictionary;
import com.zkingsoft.pojo.AjaxResult;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.services.sys.SysDataDictionaryService;
import com.zkingsoft.util.WebUtil;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
@Controller
@RequestMapping(value = "admin/sysDataDictionary")
public class SysDataDictionaryController extends BaseController{

	@Resource
	private SysDataDictionaryService sysDataDictionaryService;
	
	@Resource(name="authorityAdapter")
	private Authority  authorityAdapter;
	
	//记录编辑前的值Before_Edit_Value
	public static final String BEV="SysDataDictionary_BEV";
	public static final String fnCode = "dataDictionary";
	public static final String search = fnCode + ":search";
	public static final String edit = fnCode + ":edit";
	public static final String del = fnCode + ":del";
	public static final String add = fnCode + ":add";
	
	/**
	 * 列表显示
	 */
	@RequestMapping(value = "/showList")
	public @ResponseBody AjaxResult showList(SysDataDictionary sysDataDictionary, PaginationVO pageVo) {
		authorityAdapter.isBtnPermitted(search);
		return showList(sysDataDictionaryService, sysDataDictionary, pageVo);
	}
   	
	/**
	 * 新增或者修改页面
	 */   
	@RemoveRequestToken	
   	@RequestMapping(value = "/addOrModify")
	public @ResponseBody AjaxResult addOrModify(SysDataDictionary sysDataDictionary) {
		if (sysDataDictionary.getDicId() != null) {
			authorityAdapter.isBtnPermitted(edit);
	   		AjaxResult result=modify(sysDataDictionaryService, WebUtil.getSessionAttribute(BEV), sysDataDictionary,"sysDataDictionary");
			WebUtil.removeSessionAttribute(BEV);
			return  result;
		} else {
			authorityAdapter.isBtnPermitted(add);
			return add(sysDataDictionaryService, sysDataDictionary, "sysDataDictionary");
		}
	}
	
   	/**
	 * 进入修改界面
	 */   
	@SaveRequestToken
   	@RequestMapping(value = "/editForm")
	public String editForm(Long id) {
		authorityAdapter.isBtnPermitted(edit);
		SysDataDictionary sysDataDictionary;
		if (id != null) {
			sysDataDictionary = sysDataDictionaryService.findById(id);
			WebUtil.getRequest().setAttribute("obj", sysDataDictionary);
			WebUtil.setSessionAttribute(BEV, sysDataDictionary);
		}
		return "admin/sysDataDictionary-form";
	}
   	
   	
   	/**
	 * 删除
	 */  
 	@RequestMapping(value = "/del")
	public @ResponseBody AjaxResult del(String keys) {
 		authorityAdapter.isBtnPermitted(del);
		return remove(sysDataDictionaryService, keys);
	}
  
}