package com.zkingsoft.services.sys.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.zkingsoft.dao.sys.SysDbBackupDao;
import com.zkingsoft.model.sys.SysDbBackup;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.services.sys.SysDbBackupService;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 17:45
 */
@Service("sysDbBackupService")
public class  SysDbBackupServiceImpl implements    SysDbBackupService  {

	
	@Autowired
	private SysDbBackupDao sysDbBackupDao;
	
	
	@Override
	public int add(SysDbBackup sysDbBackup){
		
		return sysDbBackupDao.insert(sysDbBackup);
		
	}
   	
    @Override
	public int modify(SysDbBackup sysDbBackup){
	
		return sysDbBackupDao.update(sysDbBackup);
	
	}
	
    @Override
    public int modifyByMap(SysDbBackup oldSysDbBackup ,SysDbBackup newSysDbBackup) {
    	
		return 1;
    }
    
	@Override
	public int remove(List<Long> list){
	
		return sysDbBackupDao.deleteByIds(list);
	
	}

	@Override
	public int removeById(Long buId){
	
		return sysDbBackupDao.deleteById(buId);
	
	}
	
	@Override
	public int removeByModel(SysDbBackup sysDbBackup){
	
		return sysDbBackupDao.deleteByModel(sysDbBackup);
	
	}
	
	
	@Override
	public List<SysDbBackup> findInPage(SysDbBackup sysDbBackup,  PaginationVO pageVo){
	
		return sysDbBackupDao.selectInPage(sysDbBackup , pageVo);
	
	}
	
	@Override
	public List<SysDbBackup> findByModel(SysDbBackup sysDbBackup){
	
		return sysDbBackupDao.selectByModel(sysDbBackup);
	
	}
	
	@Override
	public int  findTotal(SysDbBackup sysDbBackup){
	
		return sysDbBackupDao.selectTotalRecord(sysDbBackup);
	
	}
	
	@Override
	public SysDbBackup  findById(Long buId){
	
		return sysDbBackupDao.selectById(buId);
	
	}

   	
	
	
}