package com.zkingsoft.actions.admin.bus;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.constraint.BaseController;
import javax.annotation.Resource;
import com.zkingsoft.anotations.RemoveRequestToken;
import com.zkingsoft.services.bus.BusCformService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import com.zkingsoft.anotations.SaveRequestToken;
import com.zkingsoft.pojo.AjaxResult;
import com.zkingsoft.util.WebUtil;
import com.zkingsoft.authority.MatrixAdapter;
import com.zkingsoft.model.bus.BusCform;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-28 10:12
 */
@Controller
@RequestMapping(value = "admin/busCform")
public class BusCformController extends BaseController{

	@Resource
	private BusCformService busCformService;
	
	@Resource
	private MatrixAdapter matrixAdapter;
	
	
	
	//记录编辑前的值Before_Edit_Value
	public static final String BEV="BusCform_BEV";
	
	public static final String fnCode = "BusCform";
	public static final String search = fnCode + ":search";
	public static final String edit = fnCode + ":edit";
	public static final String del = fnCode + ":del";
	public static final String add = fnCode + ":add";
	
	/**
	 * 列表显示
	 */
	@RequestMapping(value = "/showList")
	public @ResponseBody AjaxResult showList(BusCform busCform, PaginationVO pageVo) {
		matrixAdapter.isBtnPermitted(search);
		return showList(busCformService, busCform, pageVo);
	}
   	
	/**
	 * 新增或者修改页面
	 */   
	@RemoveRequestToken	
   	@RequestMapping(value = "/addOrModify")
	public @ResponseBody AjaxResult addOrModify(BusCform busCform) {
		if (busCform.getCfId() != null) {
	   		matrixAdapter.isBtnPermitted(edit);
	   		busCform.setCfId(((BusCform)WebUtil.getSessionAttribute(BEV)).getCfId());
	   		AjaxResult result=modify(busCformService, WebUtil.getSessionAttribute(this.BEV), busCform, "busCform");
			WebUtil.removeSessionAttribute(this.BEV);
			return  result;
		} else {
			matrixAdapter.isBtnPermitted(add);
			return add(busCformService, busCform, "busCform");
		}
	}
	
   	/**
	 * 进入修改界面
	 */   
	@SaveRequestToken
   	@RequestMapping(value = "/editForm")
	public String editForm(Long id) {
		matrixAdapter.isBtnPermitted(edit);
		BusCform busCform;
		if (id != null) {
			busCform = busCformService.findById(id);
			WebUtil.getRequest().setAttribute("obj", busCform);
			WebUtil.setSessionAttribute(this.BEV, busCform);
		}
		return "admin/busCform-form";
	}
   	
   	
   	/**
	 * 删除
	 */  
 	@RequestMapping(value = "/del")
	public @ResponseBody AjaxResult del(String keys) {
		matrixAdapter.isBtnPermitted(del);
		return remove(busCformService, keys);
	}
  
}