package com.zkingsoft.dao.bus;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.bus.BusCform;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-28 10:12
 */


public interface BusCformDao{

	public int insert(BusCform busCform);
   	
   	public int batchInsert(@Param("list") List<BusCform> busCformList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(BusCform busCform);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long cfId);

	public int deleteByModel(@Param("record") BusCform busCform);
	
	public List<BusCform> selectInPage(@Param("record") BusCform busCform, @Param("pageVo") PaginationVO pageVo);

	public List<BusCform> selectByModel(@Param("record") BusCform busCform);
	
	public int  selectTotalRecord(@Param("record") BusCform busCform);
	
	public BusCform  selectById(Long cfId);
	
	public BusCform  selectForUpdate(Long cfId);
	
}